
language: node_js

node_js:
  - "4.1"
  - "0.10"
  - "0.6"

# Stolen from https://github.com/leviwilson/android-travis-ci-example/blob/master/.travis.yml - thanks Levi!
before_script:
  - wget http://dl.google.com/android/android-sdk_r24-linux.tgz
  - tar -xzvf android-sdk_r24-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - npm install -g cordova ionic grunt-cli
  - ionic platform add android
  - echo 'y' | android update sdk --no-ui --force

script: grunt && ionic build
